[app]
name = "alanswap"
port="8000"
apiPort = "8100"
version = "v1"
jwtSecret = "xxx"  # jwt secret
jwtTtl = 12  # token ttl in hours


[pgsql]
host = "127.0.0.1"
port = "5432"
database = "crypto_swap"
username = "postgres"
password = "123456"

[redis]
host = "localhost"
port = "6379"
db = 1
password = ""
max_idle = 10
max_active = 0
idle_timeout = 180
poolSize=200


[[chains]]
name = "sepolia"
chain_id = 11155111
endpoint = "https://sepolia.infura.io/v3/xxx"
[[chains]]
name = "mainnet"
chain_id = 1
endpoint = "https://sepolia.infura.io/v3/xxx"

[monitor]
pprof_enable = true
pprof_port = 6060