version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: alanswap
      POSTGRES_USER: alanuser
      POSTGRES_PASSWORD: alanpasswd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      alanswap-network:
        ipv4_address: 172.18.0.2  # 固定IP地址
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alanuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass "redispasswd"
    networks:
      alanswap-network:
        ipv4_address: 172.18.0.3  # 固定IP地址
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  alanswap-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24  # 定义子网
          gateway: 172.18.0.1     # 可选：指定网关
